Add support for driving `BufferedProtocol` instances using `sock_recv_into`
beeware/gbulb pull request #60
Opened 2022-10-13 00:01 UTC by ntninja

Support for this feature is emulated for the `Pipe{Read,Write}Transport` however, since `glib.IOChannel` does not appear to expose anything similar to the `recvinto` syscall in its APIs. The emulation at least makes it possible to use `BufferedProtocol` instances without causing crashes due to API differences versus the classic `Protocol` interface at least.

## PR Checklist:

- [ ] All new features have been tested – no test code
- [x] All new features have been documented(ish)
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

2022-11-05 00:09 UTC, ntninja commented on src/gbulb/transports.py
> +                #FIXME: GLib does not actually expose the equivalent to
Note: This line caused `flake8` to cry with error E265, because there is no space between the hash sign and the word FIXME…

2022-11-05 00:09 UTC, ntninja commented
(CI passes now, but I had to disable the broken towncrier check.)

2022-12-06 01:16 UTC, freakboy3742 requested changes
Thanks for the PR (and apologies for the delay in reviewing; I apparently didn't have this repo on my Github Watch list). 

I've corrected the problem with the Towncrier configuration; and this PR looks reasonable from a first-pass review. However, in order to be merged, it requires tests for the new functionality.

2024-05-04 04:51 UTC, freakboy3742 approved these changes
I'd feel a lot better if this had tests; but empirical testing shows that it resolves #116, and the perfect is the enemy of the good, so I'll merge it. Thanks for the PR; apologies for taking so long to get to merging it.

2024-05-04 04:51 UTC, merged